<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.4" />
    <xacro:property name="base_width" value="0.2" />
    <xacro:property name="base_height" value="0.3" />
    <xacro:property name="base_mass" value="10" />

    <xacro:property name="wheel_radius" value="0.09" />
    <xacro:property name="wheel_width" value="0.05" />
    <xacro:property name="wheel_pos_x" value="${base_width/2}" />
    <xacro:property name="wheel_pos_y" value="${base_length/2 + wheel_width/2}" />
    <xacro:property name="wheel_pos_z" value="${-base_height/2}" />
    <xacro:property name="wheel_mass" value="0.6" />
    <xacro:property name="wheel_torque" value="20" />
    <xacro:property name="wheel_yaw" value="0.785398163" />



</robot>